version: '3.8'

services:
  broadcaster:
    build:
      context: ./broadcaster
      dockerfile: Dockerfile
    devices:
      - /dev/snd:/dev/snd  # For Linux audio access
    volumes:
      - ./.env:/app/.env
    depends_on:
      - server
    restart: unless-stopped
    network_mode: host  # Required for audio device access

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./models:/app/models  # Persist downloaded Whisper models
    environment:
      - CUDA_VISIBLE_DEVICES  # Pass through GPU if available
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - server
    restart: unless-stopped